spring.application.name=introduction-to-spring-boot
server.port=8080
# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/pos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=sky
spring.datasource.password=sky123

# JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
# Let Hibernate manage schema updates (will create missing tables but not drop existing)
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# tells Spring Boot - wait until JPA (Hibernate) finishes creating tables, then run data.sql
#spring.jpa.defer-datasource-initialization=true

# ensures data.sql runs every time the app starts (not only on embedded DBs like H2).
#spring.sql.init.mode=always




